name: covenant_va_desktop
description: "Covenant VA Desktop Application"
publish_to: 'none'
version: 1.0.29+30

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  dio: ^5.4.0
  shared_preferences: ^2.5.3
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  intl: ^0.20.2
  dartz: ^0.10.1
  socket_io_client: ^2.0.3+1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  url_launcher: ^6.3.2
  emoji_picker_flutter: ^3.1.0
  flutter_webrtc: ^1.3.1
  ffi: ^2.2.0
  file_picker: ^10.3.10
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/notification.mp3
    - assets/images/fav.png
    - assets/images/fav2.png
    - assets/images/fav3.png
    - assets/images/fav.ico
    - assets/images/mascot/idle.png
    - assets/images/mascot/typing.png
    - assets/images/mascot/peeking.png
    - assets/images/mascot/loading.png
    - assets/images/mascot/success.png
    - assets/images/mascot/error.png

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf